// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD19PTRYBUIr0BALFHBfrlvs-P0UY5p2KM',
    appId: '1:877199794261:web:e29078fab6c286b8b1b4dc',
    messagingSenderId: '877199794261',
    projectId: 'booking-camp-8b08b',
    authDomain: 'booking-camp-8b08b.firebaseapp.com',
    storageBucket: 'booking-camp-8b08b.appspot.com',
    measurementId: 'G-2WX91ZLSBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXdhEpiv6v86VSDNiladnM4dy8qhsW55I',
    appId: '1:877199794261:android:939f77976e2373f3b1b4dc',
    messagingSenderId: '877199794261',
    projectId: 'booking-camp-8b08b',
    storageBucket: 'booking-camp-8b08b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwOip2KPXtQWtwib4IC9AOcdAgB75x3I4',
    appId: '1:877199794261:ios:5565ed0a9fbb7d82b1b4dc',
    messagingSenderId: '877199794261',
    projectId: 'booking-camp-8b08b',
    storageBucket: 'booking-camp-8b08b.appspot.com',
    iosBundleId: 'com.example.flutterMotobike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwOip2KPXtQWtwib4IC9AOcdAgB75x3I4',
    appId: '1:877199794261:ios:5565ed0a9fbb7d82b1b4dc',
    messagingSenderId: '877199794261',
    projectId: 'booking-camp-8b08b',
    storageBucket: 'booking-camp-8b08b.appspot.com',
    iosBundleId: 'com.example.flutterMotobike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD19PTRYBUIr0BALFHBfrlvs-P0UY5p2KM',
    appId: '1:877199794261:web:2d4ed5d7671fedecb1b4dc',
    messagingSenderId: '877199794261',
    projectId: 'booking-camp-8b08b',
    authDomain: 'booking-camp-8b08b.firebaseapp.com',
    storageBucket: 'booking-camp-8b08b.appspot.com',
    measurementId: 'G-V4Q4EZRG44',
  );
}
